image: php:8.2-alpine

before_script:
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install --no-interaction --prefer-dist
  - composer require --dev phpunit/phpunit
  - composer update
  

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the project..."

test:
  stage: test
  script:
    - echo "Running tests... "
     - ./vendor/bin/phpunit
 

deploy:
  stage: deploy
  script:
    - echo "Deploying the project... "



