image: php:8.2-alpine

before_script:
  - apk update && apk add curl zip unzip tar
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install --no-interaction --prefer-dist
  - composer require --dev phpunit/phpunit
  - composer update
  

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the project..."
     - php -r "file_put_contents('build/version.txt', date('Y-m-d H:i:s'));"
    - zip -r build/project.zip . -x "build/*" -x ".git/*"
  artifacts:
    expose_as: 'artifact_build'
    paths: ['build/version.txt']  

test:
  stage: test
  script:
    - echo "Running tests... "
     - ./vendor/bin/phpunit --log-junit=build/phpunit-report.xml
  artifacts:
    paths: ['build/phpunit-report.xml']
 

deploy:
  stage: deploy
  script:
    - echo "Deploying the project... "



