before_script:
  - apk update
  - apk add curl zip unzip tar docker
  - apk add php php-curl php-json php-dom php-phar php-iconv php-openssl php-mbstring
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install --no-interaction --prefer-dist
  - composer require --dev phpunit/phpunit
  - composer update
  - ls -al build/
  - chmod -R 775 build/

stages:
  - build
  - test
  - code-quality
  - deploy

build:
  stage: build
  script:
    - echo "Building the project..."

test:
  stage: test
  script:
    - echo "Running tests... "

code_quality:
  image: adamculp/php-code-quality
  script:
    - vendor/bin/phpcs --standard=PSR2 app/
    - vendor/bin/phpmd app/ text codesize,unusedcode,naming,design
    #- vendor/bin/phpstan analyze app/
    - docker run --rm -v $(pwd):/app adamculp/php-code-quality phpstan analyze -c phpstan.neon > build/phpstan-report.txt
  artifacts:
    paths: ['build/phpstan-report.txt']
    reports:
      codequality: build/logs/

deploy:
  stage: deploy
  script:
    - echo "Deploying the project... "
    - echo "Generating version.txt file..."
    - echo "$(date +%Y-%m-%d-%H:%M:%S)" > build/version.txt
  artifacts:
    paths: ['build/version.txt']
